# 实验1
1、Numpy基础实验：请生成如图1所示的对称矩阵，并保存成csv文件

$$\left[
\begin{matrix}
 2 & -8 &  0 &  3 \\
-8 &  0 & -4 &  6 \\
 0 & -4 & -1 & -2 \\
 3 &  6 & -2 &  1
\end{matrix}
\right]
$$


In [1]:
import numpy as np
sarray = np.random.randint(-10,10,size=(4, 4))
print('随机生成4*4 整数矩阵：\n',sarray)
sarray

随机生成4*4 整数矩阵：
 [[ 2  2  1  8]
 [-8  5  4 -1]
 [-2 -8  3 -8]
 [-9  8  3  9]]


array([[ 2,  2,  1,  8],
       [-8,  5,  4, -1],
       [-2, -8,  3, -8],
       [-9,  8,  3,  9]])

In [2]:
import numpy as np
sarray = np.random.randint(-10,10,size=(4, 4))
print('随机生成4*4 整数矩阵：\n',sarray)
sarray = np.triu(sarray)
print('变成上三角矩阵：\n',sarray)
sarray += sarray.T -np.diag(sarray.diagonal())
print('生成4*4 对称矩阵：\n',sarray)
np.savetxt("D:\sarrays.csv", sarray, fmt="%d", delimiter=",")

随机生成4*4 整数矩阵：
 [[ -2  -3   2   4]
 [ -8   6  -1  -9]
 [-10  -7   0   5]
 [  1   3  -1  -7]]
变成上三角矩阵：
 [[-2 -3  2  4]
 [ 0  6 -1 -9]
 [ 0  0  0  5]
 [ 0  0  0 -7]]
生成4*4 对称矩阵：
 [[-2 -3  2  4]
 [-3  6 -1 -9]
 [ 2 -1  0  5]
 [ 4 -9  5 -7]]


In [3]:
import numpy as np
my_array = np.array([[2, -8, 0, 3],[-8, 0, -4, 6], [0, -4, -1, -2], [3, 6, -2, 1]])
print("创建的对称矩阵为：\n",my_array)
np.savetxt("D:\my_array.csv", my_array, fmt="%d", delimiter=",")

创建的对称矩阵为：
 [[ 2 -8  0  3]
 [-8  0 -4  6]
 [ 0 -4 -1 -2]
 [ 3  6 -2  1]]


# 实验2
2、Numpy数组切片：请将矩阵[[1, 2, 3], [4, 5, 6], [7, 8, 9]]对角线元素取出并打印。

In [4]:
import numpy as np
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("原数组为：\n",my_array)
print("第一个对角线元素：\n", my_array[0:1, 0:1])
print("第二个对角线元素：\n", my_array[1:2, 1:2])
print("第三个对角线元素：\n", my_array[2:3, 2:3])
my_array = np.diagonal(my_array)
print("对角线元素汇总：\n", my_array)

原数组为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
第一个对角线元素：
 [[1]]
第二个对角线元素：
 [[5]]
第三个对角线元素：
 [[9]]
对角线元素汇总：
 [1 5 9]


# 实验3
3、Numpy数组切片进阶：请将矩阵[[1, 2, 3], [4, 5, 6], [7, 8, 9]]中的第1列与第3行取出，并进行合并。

In [5]:
import numpy as np
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("原数组：\n", my_array)
print("第一列数组：\n", my_array[: ,0])
print("第三行数组：\n", my_array[2, :])
print("第一三行合并数组方式一：\n", np.vstack((my_array[: ,0], my_array[2, :])))
print("第一三行合并数组方式二：\n", np.concatenate((my_array[: ,0], my_array[2, :]), axis = 0))

原数组：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
第一列数组：
 [1 4 7]
第三行数组：
 [7 8 9]
第一三行合并数组方式一：
 [[1 4 7]
 [7 8 9]]
第一三行合并数组方式二：
 [1 4 7 7 8 9]


3、Numpy数组切片进阶：请将矩阵[[1, 2, 3], [4, 5, 6], [7, 8, 9]]中的第1行与第3行取出，并进行合并。

In [6]:
import numpy as np
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("原数组：\n", my_array)
print("第一列数组：\n", my_array[: ,0])
print("第三行数组：\n", my_array[2, :])
print("第一三行合并数组方式一：\n", np.vstack((my_array[0 ,:], my_array[2, :])))
print("第一三行合并数组方式二：\n", np.concatenate((my_array[0 ,:], my_array[2, :]), axis = 0))

原数组：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
第一列数组：
 [1 4 7]
第三行数组：
 [7 8 9]
第一三行合并数组方式一：
 [[1 2 3]
 [7 8 9]]
第一三行合并数组方式二：
 [1 2 3 7 8 9]


# 实验4
4、Pandas实验：随机生成'张三','李四','王五'的期中考试成绩数据result，他们的成绩包括'语文','英语','数学','python'，成绩分值在90至150之间。如下所示：

        语文   英语   数学   python
    张三   155    147    10     135
    李四   240    251    252    220
    王五   156    135    154    150

要求：
1. 生成刘六的数据，并加入DataFrame中(1分)。
2. 将语文修改为java(1分)。
3. 增加C语言成绩，成绩在 70至90之间随机生成(2分)。
4. 按python成绩从高至低进行排序(1分)。

In [7]:
import pandas as pd
import numpy as np

## 随机生成'张三','李四','王五'的期中考试成绩数据
## 成绩包括'语文','英语','数学','python'，成绩分值在90至150之间
df1 = pd.DataFrame(np.random.randint(90,150,size=(3, 4)),columns=['语文', '英语', '数学', 'python'], index=['张三', '李四', '王五'])
print("随机生成期中考试成绩：\n",df1)

## 生成刘六的数据
df2 = pd.DataFrame(np.random.randint(90,150,size=(1, 4)),columns=['语文', '英语', '数学', 'python'], index=['刘六']) 
print("随机生成刘六的期中考试成绩：\n",df2)
df = pd.concat([df1,df2])
print("刘六加入以后的期中考试成绩：\n",df)

## 将语文改成java
df = df.rename(columns={'语文':'java'})
print("语文改成java后的期中考试成绩：\n",df)

## 增加C语言成绩
df3 = np.random.randint(70,90,size=(4, 1))
print("随机生成的c语言期中考试成绩：\n",df3)
df.insert(df.shape[1], 'c语言', df3)
print("增加c语言后的期中考试成绩：\n",df)

## 排序
df = df.sort_values(by='python',ascending=False)
print("按python成绩从高到底排序以后的期中考试成绩：\n",df)

随机生成期中考试成绩：
      语文   英语   数学  python
张三  116  138  115     119
李四  100  147  139      97
王五  107  127  139     113
随机生成刘六的期中考试成绩：
      语文  英语   数学  python
刘六  124  97  119     145
刘六加入以后的期中考试成绩：
      语文   英语   数学  python
张三  116  138  115     119
李四  100  147  139      97
王五  107  127  139     113
刘六  124   97  119     145
语文改成java后的期中考试成绩：
     java   英语   数学  python
张三   116  138  115     119
李四   100  147  139      97
王五   107  127  139     113
刘六   124   97  119     145
随机生成的c语言期中考试成绩：
 [[77]
 [83]
 [70]
 [83]]
增加c语言后的期中考试成绩：
     java   英语   数学  python  c语言
张三   116  138  115     119   77
李四   100  147  139      97   83
王五   107  127  139     113   70
刘六   124   97  119     145   83
按python成绩从高到底排序以后的期中考试成绩：
     java   英语   数学  python  c语言
刘六   124   97  119     145   83
张三   116  138  115     119   77
王五   107  127  139     113   70
李四   100  147  139      97   83


# 参考资料
> [DataFrame 新增里的五种方法](https://blog.csdn.net/qq_35318838/article/details/102720553)  
> [创建对称矩阵（numpy）](https://blog.csdn.net/lanchunhui/article/details/50353637)  
> [Pandas 生成随机整数序列](https://blog.csdn.net/weixin_35757704/article/details/109295540)  
> [python 用numpy生成多维随机数组](https://blog.csdn.net/u013533991/article/details/41923837)